---
permalink: pretty
title: Humanae salutis monumenta
tagline: ', an annotated digital edition'
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
url: http://emory-libraries-ecds.github.io/digitaledition-jekylltheme/
baseurl: /digitaledition-jekylltheme
relative_links: false
homepage_image: http://webprd001.library.emory.edu/readux/books/emory:b6zzh/pages/emory:gkkd2/single-page/
author:
  name:
  url:
  email:
version: 1.0.0
show_annotation_author: true
readux_url: http://webprd001.library.emory.edu/readux/books/emory:b6zzh/
readux_pdf_url: http://webprd001.library.emory.edu/readux/books/emory:b6zzh/pdf/#page=2
publication_info:
  title: Humanae salutis monumenta
  author: Arias Montano, Benito, 1527-1598.
  date: 1571 [i.e. 1583
collections:
  annotations:
    output: true
  volume_pages:
    output: true
    permalink: /pages/:path/
defaults:

- scope:
    path: ''
    type: volume_pages
  values:
    layout: volume_page
    short_label: 'p.'
    extra_js:
        - deepzoom.js
        - openseadragon.min.js
        - volume-page.js

image_size:
  thumbnail:
    width: 208
    height: 300

